---
- name: Deploy Wild-West-Web
  hosts: webserver
  user: root
  become: true

  tasks:
    - name: All packages are up to date
      ansible.builtin.package:
        name: "*"
        state: latest
