name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create empty dist folder
      run: mkdir -m 0777 dist/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag astrobuild:latest
    - name: Run Astrobuild
      run: docker run --rm -v $(pwd):/var/source astrobuild:latest
