name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build artifacts
      run: |
        mkdir -m 0777 dist/
        docker build . --file Dockerfile --tag astrobuild:latest
        docker run --rm -v $(pwd):/var/source astrobuild:latest

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4  
      with:
        name: site_dist
        path: dist
